"""
poc.py: generate a C/C++ DeviceIoControl harness skeleton from discovered IOCTLs.

The output is a starting point for manual testing/fuzzing, not a working exploit:
buffer sizes and contents are placeholders. IOCTLs are emitted highest-severity
first so the most interesting ones are at the top of main().
"""

from DriverBuddyReloaded import config, ioctl_decoder

_FALLBACK_DEVICE_PATH = r"\\.\CHANGEME"
_KERNEL_PATH_PREFIXES = ("\\DosDevices\\", "\\??\\", "\\Device\\")
_DEFAULT_BUF_SIZE = 0x100
_USERMODE_PATH_PREFIX = r"\\."


def _device_user_path(rep):
    """Best-effort user-mode device path (\\\\.\\Name) from device-name findings."""
    candidates = []
    for finding in rep.by_category("device_name"):
        name = finding.title or ""
        for prefix in _KERNEL_PATH_PREFIXES:
            if prefix in name:
                tail = name.rsplit(prefix, 1)[-1]
                candidates.append((prefix, tail))
                break

    # Prefer DosDevices or ??/ over Device.
    for preferred in ("\\DosDevices\\", "\\??\\"):
        for prefix, tail in candidates:
            if prefix == preferred and tail:
                return _USERMODE_PATH_PREFIX + "\\" + tail

    # Fall back to any Device\ candidate.
    for prefix, tail in candidates:
        if tail:
            return _USERMODE_PATH_PREFIX + "\\" + tail

    return _FALLBACK_DEVICE_PATH


def _c_wide_literal(device_path):
    """Render a Python path string as a C wide-string literal (backslashes doubled)."""
    escaped = device_path.replace("\\", "\\\\")
    return f'L"{escaped}"'


def _build_c_source(valid, device_literal):
    """Return all C source lines for the harness. `valid` is a list of (finding, code) pairs."""
    lines = [
        "// Auto-generated by Driver Buddy Reloaded - IOCTL PoC harness skeleton",
        f"// Driver : {config.driver_name()}",
        f"// SHA-256: {config.input_sha256()}",
        "// NOTE   : buffer sizes/contents are placeholders - adjust before use.",
        "",
        "#include <Windows.h>",
        "#include <stdio.h>",
        "",
        "// ---- Discovered IOCTLs (severity-sorted) ----",
    ]
    for finding, code in valid:
        device_name = finding.data.get("device_name", "?")
        method_name = finding.data.get("method_name", "?")
        access_name = finding.data.get("access_name", "?")
        severity = config.severity_name(finding.severity)
        lines.append(
            f"{ioctl_decoder.get_define(code)}"
            f"  // [{severity}] {device_name} / {method_name} / {access_name}"
        )

    buf_size = hex(_DEFAULT_BUF_SIZE)
    lines += [
        "",
        "int main(void) {",
        f"    HANDLE h = CreateFileW({device_literal},",
        "                           GENERIC_READ | GENERIC_WRITE, 0, NULL,",
        "                           OPEN_EXISTING, 0, NULL);",
        "    if (h == INVALID_HANDLE_VALUE) {",
        "        printf(\"[!] CreateFile failed: %lu\\n\", GetLastError());",
        "        return 1;",
        "    }",
        "",
        "    DWORD bytesReturned = 0;",
        f"    BYTE  inBuf[{buf_size}]  = {{ 0 }};",
        f"    BYTE  outBuf[{buf_size}] = {{ 0 }};",
        "",
    ]
    for finding, code in valid:
        severity = config.severity_name(finding.severity)
        define = ioctl_decoder.define_name(code)
        lines.append(f"    // [{severity}] {finding.title}")
        lines.append(
            f"    DeviceIoControl(h, {define}, inBuf, sizeof(inBuf), "
            "outBuf, sizeof(outBuf), &bytesReturned, NULL);"
        )
        lines.append("")
    lines += [
        "    CloseHandle(h);",
        "    return 0;",
        "}",
        "",
    ]
    return lines


def generate(rep, path):
    """Write a C harness for every IOCTL finding in `rep` to `path`."""
    ioctls = rep.by_category("ioctl")
    if not ioctls:
        rep.info("[!] No IOCTLs discovered; skipping PoC harness generation")
        return False

    # Highest severity first; stable within a severity by address.
    ioctls = sorted(ioctls, key=lambda finding: (-finding.severity, finding.ea))
    valid = [(finding, finding.data["code"]) for finding in ioctls if finding.data.get("code") is not None]

    device_literal = _c_wide_literal(_device_user_path(rep))
    lines = _build_c_source(valid, device_literal)

    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
        rep.info(f'[>] Saved IOCTL PoC harness to "{path}"')
        return True
    except OSError as e:
        rep.info(f'[!] Could not write PoC harness to "{path}": {e}')
        return False
