"""
poc.py: generate a C/C++ DeviceIoControl harness skeleton from discovered IOCTLs.

The output is a starting point for manual testing/fuzzing, not a working exploit:
buffer sizes and contents are placeholders. IOCTLs are emitted highest-severity
first so the most interesting ones are at the top of main().
"""

from DriverBuddyReloaded import config, ioctl_decoder


def _device_user_path(rep):
    """Best-effort user-mode device path (\\\\.\\Name) from device-name findings."""
    for f in rep.by_category("device_name"):
        name = f.title or f.detail or ""
        if "\\Device\\" in name or "\\DosDevices\\" in name or "\\??\\" in name:
            tail = name.rsplit("\\", 1)[-1]
            if tail:
                return r"\\.\%s" % tail
    return r"\\.\CHANGEME"


def _c_wide_literal(path):
    """Render a Python path string as a C wide-string literal (backslashes doubled)."""
    return 'L"%s"' % path.replace("\\", "\\\\")


def generate(rep, path):
    """Write a C harness for every IOCTL finding in `rep` to `path`."""
    ioctls = rep.by_category("ioctl")
    if not ioctls:
        rep.info("[!] No IOCTLs discovered; skipping PoC harness generation")
        return False

    # Highest severity first; stable within a severity by address.
    ioctls = sorted(ioctls, key=lambda f: (-f.severity, f.ea))
    device_literal = _c_wide_literal(_device_user_path(rep))

    lines = [
        "// Auto-generated by Driver Buddy Reloaded - IOCTL PoC harness skeleton",
        "// Driver : %s" % config.driver_name(),
        "// SHA-256: %s" % config.input_sha256(),
        "// NOTE   : buffer sizes/contents are placeholders - adjust before use.",
        "",
        "#include <Windows.h>",
        "#include <stdio.h>",
        "",
        "// ---- Discovered IOCTLs (severity-sorted) ----",
    ]
    for f in ioctls:
        code = f.data.get("code")
        if code is None:
            continue
        lines.append("%s  // [%s] %s / %s / %s" % (
            ioctl_decoder.get_define(code),
            config.severity_name(f.severity),
            f.data.get("device_name", "?"),
            f.data.get("method_name", "?"),
            f.data.get("access_name", "?")))

    lines += [
        "",
        "int main(void) {",
        "    HANDLE h = CreateFileW(%s," % device_literal,
        "                           GENERIC_READ | GENERIC_WRITE, 0, NULL,",
        "                           OPEN_EXISTING, 0, NULL);",
        "    if (h == INVALID_HANDLE_VALUE) {",
        "        printf(\"[!] CreateFile failed: %lu\\n\", GetLastError());",
        "        return 1;",
        "    }",
        "",
        "    DWORD bytesReturned = 0;",
        "    BYTE  inBuf[0x100]  = { 0 };",
        "    BYTE  outBuf[0x100] = { 0 };",
        "",
    ]
    for f in ioctls:
        code = f.data.get("code")
        if code is None:
            continue
        lines.append("    // [%s] %s" % (config.severity_name(f.severity), f.title))
        lines.append("    DeviceIoControl(h, %s, inBuf, sizeof(inBuf), "
                     "outBuf, sizeof(outBuf), &bytesReturned, NULL);" % ioctl_decoder.define_name(code))
        lines.append("")
    lines += [
        "    CloseHandle(h);",
        "    return 0;",
        "}",
        "",
    ]

    try:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
        rep.info("[>] Saved IOCTL PoC harness to \"{}\"".format(path))
        return True
    except IOError as e:
        rep.info("[!] Could not write PoC harness to \"{}\": {}".format(path, e))
        return False
